public with sharing class ExchangeRateCalloutService {
   @is test 
    public ExchangeRateCalloutService() {
        hello world
hello world

hello world

hello world

hello world

hello world

hello world

hello world


hello world

hello world


hello world

hello world

hello world


hello world

hello world

hello world

hello world


hello world

hello world

hello world


hello world

hello world




    }
}
